const CREDS={"mcarso123": {"hash": "368c04a431d90f4a11cc7b15ae6d5d9d3e1f5f506da520ab0de4e59df12f889a", "role": "STAFF"}, "night56621": {"hash": "8ea41afb8b20eb453740deadc16c0617d2530a37315cac4de83abeda03367549", "role": "STAFF"}, "stmpylonghead23": {"hash": "e7d70bc1a30652509bbfea896c553f79306ec0998c82cbcfdce11ee3dda016f2", "role": "STAFF"}, "luna_ellie439": {"hash": "c2ab496abf8c04134422877a9608262159c7aec5fbb09cff2769794c74e906b0", "role": "STAFF"}, "angelfiber40": {"hash": "5ee047eba4ef9c6cadcf3bb73f83303a7180b434236902fd56b9731fba92d681", "role": "STAFF"}, "zmbzay": {"hash": "1d24a732e03a49b42c12f4a52198c87418f80d94cf8bb4f1f6f28410f0c903fd", "role": "STAFF"}, "officialdroxz": {"hash": "3ae5cb3f288ea38572c37b95f4b9306f72ffd2f405f0c4d024bba12387186e5f", "role": "OWNER"}, "mrgamer4654": {"hash": "2eb6aceb865feeceedcbf93f7280bcf5967d4421a195b8d3395452c162b46204", "role": "STAFF"}, "blake2310288": {"hash": "0eb03c64462b47149a9f49c01a246828e735e5ff47def36e993f536bded9e4b4", "role": "STAFF"}, "blondracer04": {"hash": "97503e15dbd26974e34d20345fb5606efc05b0fbbcd17cea12d8127b31615368", "role": "STAFF"}, "z9vh": {"hash": "c6405ed9825efbcd801ed780b222f2d2e4521cceae7a37208e154524e4e10859", "role": "STAFF"}, "code3_ohio": {"hash": "dc7f56dd3274d0e168d0e8dd975fa4df89ed0fdf079bda2d5585edc5c3369418", "role": "STAFF"}, "womp.420": {"hash": "3ef664f0a703dfabc57bd93b3463f1e1a19ec8443d272e31fe4968a241e0f217", "role": "STAFF"}};
const app=document.getElementById('app');
const key='nexresponse_network_data_v2';
const blank={updates:[],training:[],warnings:[],schedules:[],tasks:[]};
let data=JSON.parse(localStorage.getItem(key)||'null')||blank;
let current=localStorage.getItem('nr_user');
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function save(){localStorage.setItem(key,JSON.stringify(data))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function loginView(){app.innerHTML=`<main class="shell"><section class="card login"><div class="brand">NexResponse <span class="accent">Network</span></div><p class="muted">Private staff access</p><div class="notice">This GitHub Pages version works as a demo, but records are saved only on this device until a secure database is connected.</div><form id="login"><input class="input" id="u" placeholder="Username" required><input class="input" id="p" type="password" placeholder="Password" required><button class="btn">Log in</button><p id="err" class="muted"></p></form></section></main>`;document.getElementById('login').onsubmit=async e=>{e.preventDefault();const u=document.getElementById('u').value.trim().toLowerCase(),p=document.getElementById('p').value;const c=CREDS[u];if(c&&await sha256(p)===c.hash){localStorage.setItem('nr_user',u);current=u;dashboard()}else document.getElementById('err').textContent='Incorrect username or password.'}}
function records(type){return data[type].map(x=>`<div class="item"><b>${esc(x.title||x.staff||x.course)}</b>${x.status?` <span class="badge">${esc(x.status)}</span>`:''}<p>${esc(x.details||x.reason||x.notes||'')}</p><small class="muted">${esc(x.meta||'')}</small></div>`).join('')||'<p class="muted">No records yet.</p>'}
function dashboard(){const role=CREDS[current]?.role||'STAFF';app.innerHTML=`<main class="shell"><header class="top"><div><div class="brand">NexResponse <span class="accent">Network</span></div><div class="muted">Logged in as ${esc(current)} · ${role}</div></div><button id="logout" class="btn secondary">Log out</button></header><div class="notice"><b>Network announcement:</b> Welcome to the new NexResponse Network staff panel. This panel organizes training, development, tasks, discipline, and schedules.</div><div class="tabs" id="tabs"></div><section id="panel"></section></main>`;document.getElementById('logout').onclick=()=>{localStorage.removeItem('nr_user');current=null;loginView()};const tabs=[['updates','Development Updates'],['tasks','Task Assignments'],['training','Training Records'],['warnings','Warnings'],['schedules','Schedules']];const t=document.getElementById('tabs');tabs.forEach(([id,label],i)=>{const b=document.createElement('button');b.className='tab'+(i?'':' active');b.textContent=label;b.onclick=()=>{[...t.children].forEach(x=>x.classList.remove('active'));b.classList.add('active');show(id,role)};t.appendChild(b)});show('updates',role)}
function show(type,role){const labels={updates:'Development Updates',tasks:'Task Assignments',training:'Training Records',warnings:'Warnings & Discipline',schedules:'Staff Schedules'};const panel=document.getElementById('panel');panel.innerHTML=`<div class="grid"><section class="card"><h2>${labels[type]}</h2>${records(type)}</section><section class="card"><h2>Add Record</h2>${form(type,role)}</section></div>`;const f=document.getElementById('recordForm');if(f)f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);const rec=Object.fromEntries(fd.entries());rec.status=type==='updates'?'PENDING':(rec.status||'ACTIVE');rec.meta=`Added by ${current} · ${new Date().toLocaleString()}`;data[type].unshift(rec);save();show(type,role)}}
function form(type,role){if(type==='warnings'&&role!=='OWNER')return '<p class="muted">Only ownership can add disciplinary records.</p>';if(type==='updates')return `<form id="recordForm"><input class="input" name="title" placeholder="Update title" required><textarea class="textarea" name="details" placeholder="What was updated?" required></textarea><button class="btn">Submit as Pending</button></form>`;if(type==='tasks')return `<form id="recordForm"><input class="input" name="title" placeholder="Task title" required><textarea class="textarea" name="details" placeholder="Task details" required></textarea><input class="input" name="staff" placeholder="Assigned staff username"><button class="btn">Add Task</button></form>`;if(type==='training')return `<form id="recordForm"><input class="input" name="staff" placeholder="Staff username" required><input class="input" name="course" placeholder="Training name" required><textarea class="textarea" name="notes" placeholder="Trainer and notes"></textarea><button class="btn">Add Training Record</button></form>`;if(type==='warnings')return `<form id="recordForm"><input class="input" name="staff" placeholder="Staff username" required><input class="input" name="title" placeholder="Warning level" required><textarea class="textarea" name="reason" placeholder="Reason" required></textarea><button class="btn">Add Warning</button></form>`;return `<form id="recordForm"><input class="input" name="staff" placeholder="Staff username" required><input class="input" name="title" placeholder="Shift / event title" required><textarea class="textarea" name="details" placeholder="Date, time, timezone, and notes" required></textarea><button class="btn">Add Schedule</button></form>`}
current&&CREDS[current]?dashboard():loginView();